### ISSUE TITLE
Get User by Id

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-nodejs-be#11]
When I am trying to take user by id which do not exists, I am receiving error 500. This is not accepted. Please, return code 404 with message - User with this id do not exists.

**Comment by BairamovAllaz** [comment]
Hey. I'd like to contribute to your project. I can start with this.Claim...

**Comment by DamyanBG** [comment]
@BairamovAllaz welcome!

I hope the description of the issue is enough.
