### ISSUE TITLE
CORS problem

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-nodejs-be#122]
When I deploy the NodeJS application on Azure and playing with the Front End, I can see some error:

![cors error](https://user-images.githubusercontent.com/93829069/210739732-d630d4c1-e148-43bb-939a-c8c213f5bfe1.PNG)

So we have to fix that.

Link to the FE repository - https://github.com/DamyanBG/real-estate-react-app

**Comment by Pavan-Nambi** [comment]
hey @DamyanBG tht link is pointing me to issues of node js...

**Comment by DamyanBG** [comment]
@Pavan-Nambi  yeah, sorry. I fixed it.

**Comment by DamyanBG** [comment]
Fixed by me, it was Azure related problem.
