### ISSUE TITLE
Clean up the MongoDB database

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-nodejs-be#127]
During initial implementation we created a lot of dump data. We have to clean up the database. The database is deployed on Azure CosmosDB. I will provide the connection string to the database for the assignee.

**Comment by rhinoxD** [comment]
!assign

**Comment by DamyanBG** [comment]
Give me email address to send you the connection string to the Database.

You can delete all existing data.

**Comment by rhinoxD** [comment]
shivamsk0721@gmail.com

**Comment by DamyanBG** [comment]
Sent

**Comment by rhinoxD** [comment]
Received

**Comment by DamyanBG** [comment]
My free subscription to Azure expired, so this issue will be closed. I do not plan to pay soon for the service.
