### ISSUE TITLE
Homes CRUD operations Authorization

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-nodejs-be#147]
First take a look at #145 

Home can be created from User with role seller.

Home can be deleted from admin or from home owner.

Home info can be changed from admin or from home owner.

All users - signed in or not can take information for home.

**Comment by DamyanBG** [comment]
@AyoubTahir

**Comment by DamyanBG** [comment]
You have to leave at least 1 comment to assign tasks to you.

**Comment by AyoubTahir** [comment]
Yeah, you're right

**Comment by AyoubTahir** [comment]
You can close this one after merging my request
