### ISSUE TITLE
Land CRUD operations Authorization

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-nodejs-be#148]
Land is similar like Home, so please, take a look at #147

**Comment by AyoubTahir** [comment]
May I work on this task? Before proceeding, I believe that currently, anyone can perform CRUD operations without being authenticated. I plan to implement middleware to verify tokens on every request.

**Comment by DamyanBG** [comment]
Okay.

**Comment by DamyanBG** [comment]
Please, take a look at #155 when implementing your code. The tests now are running without jwt.

**Comment by AyoubTahir** [comment]
I just finished verifyToken middleware now only the authenticated users can do land crud operations.
Now I'm working on authorization, you are using the roles "admin", "seller", and "user", right?

**Comment by DamyanBG** [comment]
Yes

**Comment by DamyanBG** [comment]
I just merged your work on development and started testing. I can see that get all lands and get land by id requires the user to be authenticated. If you read the description, you will find out that the behavior for lands must to be like homes. And in the homes issue there is written - All users - signed in or not can take information for home.

**Comment by AyoubTahir** [comment]
Ah, I forgot to remove the auth middleware when I was debugging getAllLands but for getLandById its working fine without authentication,
I think I will fix it with this issue #147 because it's related, you can assign me to it

**Comment by AyoubTahir** [comment]
You can close this one too after merging my request
