### ISSUE TITLE
Mock up for authentication and authorization

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-nodejs-be#155]
When we have implemented authentication and authorization, I think we will have problem with the tests. We have to use some mock up.

**Comment by DamyanBG** [comment]
@AyoubTahir do you will work on tests too?

**Comment by AyoubTahir** [comment]
Yeah I will just assign me

**Comment by AyoubTahir** [comment]
I am having trouble adding an authorization header to my request, and it seems like there is a problem with supertest

const res = await request(app).delete(`/land`).set('Authorization', `Bearer ${token}`);

Do you have any idea?

**Comment by AyoubTahir** [comment]
Never mind its working now.
