### ISSUE TITLE
Actions after deleting User

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-nodejs-be#161]
When delete User action is triggered, delete all related data to this user in the database - homes, lands, messages, meetings, visitations,

**Comment by muttaqin1** [comment]
Hey @DamyanBG! 
I am interested to contribute on this issue.

**Comment by DamyanBG** [comment]
Done

**Comment by muttaqin1** [comment]
okay i am working on it.

**Comment by muttaqin1** [comment]
@DamyanBG 
I have send a pr.If you have time please review it.

**Comment by DamyanBG** [comment]
Hello, I will take a look today, thank you for the effort!
