### ISSUE TITLE
Visitations model changes

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-nodejs-be#162]
Visitations have to contains date, start hour, end hour, organizator_id, home_id and address.

**Comment by safil-badarudeen** [comment]
i am a mern developer , with my knowledge i could help you with most of issue , let me work on issues one at a time , I came from your front end repository , assign me for this one,

**Comment by DamyanBG** [comment]
Assigned.

**Comment by safil-badarudeen** [comment]
start_date: {
        type: String,
        required: true,
    },
    end_date: {
        type: String,
        required: true,
    }

in this particualr instance type :Date is more accurate . what do you think?

**Comment by safil-badarudeen** [comment]
did you made it as string for any special purposes?

**Comment by DamyanBG** [comment]
I agree with date.

**Comment by DamyanBG** [comment]
@safil-badarudeen 
![1](https://user-images.githubusercontent.com/93829069/214041904-22141456-c4b2-4a77-b85e-35e58a05233c.PNG)
![2](https://user-images.githubusercontent.com/93829069/214041910-6ace3bae-0af9-4c7c-a77f-b1d8bf7be149.PNG)

**Comment by safil-badarudeen** [comment]
thanks man i was so confused about it

**Comment by safil-badarudeen** [comment]
can i make a another pull request  now?

**Comment by safil-badarudeen** [comment]
@DamyanBG

**Comment by DamyanBG** [comment]
I made everything, thank you
