### ISSUE TITLE
Get all users endpoint filters

### ISSUE THREAD

**Issue by BairamovAllaz** [DamyanBG/real-estate-nodejs-be#19]
Would be great to create a route which allows getting all users...
For instance /all-users.
I can do.

**Comment by DamyanBG** [comment]
You can take a closer look at route /users - from there we are taking all users.

**Comment by DamyanBG** [comment]
If you want you can make logic to get users based on filters. For example get all admins, get all brokers, get all users. Feel free to decide the routes and files architecture.

**Comment by BairamovAllaz** [comment]
I think it will be good to put them to same file..

**Comment by DamyanBG** [comment]
OK. There is existing file users. Feel free to implement the filters.

**Comment by DamyanBG** [comment]
Good job !
