### ISSUE TITLE
Implement JWT authentication

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-nodejs-be#21]
When the type of authentication is chosen in #20 issue, it is time to be implemented.

Implement user login functionality on route /login . It must contains email and password. If the user is not existing or the user is not sending correct password, return Bad Request with message Wrong email or password.

Implement user logout functionality on route /logout .

IMPORTANT ! IMPLEMENT ONLY AUTHENTICATION, NOT AUTHORIZATION !

**Comment by tihomirtx88** [comment]
What about register ?

**Comment by DamyanBG** [comment]
For now we can use POST request on /user route.

**Comment by DamyanBG** [comment]
@edesuccess54 Implemented this issue.
