### ISSUE TITLE
Tests related to Home CRUD 

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-nodejs-be#29]
Write tests related to Home CRUD operations.

I think it is good idea to have some tests for CRUD operations at all. Here it this task we can start with the CRUD operations for the Homes Model. Here are more explicit requirements:
- use whatever test library you want, there are no tests for now, so you have to add some library
- write unit and integration tests for GET, POST, PUT and DELETE requests on /home
- write tests for GET request on /homes
- write tests for services related to Homes model, test are they working properly 

The requirements for the routes:
- on route /home for GET request we have to provide request with body which contains home_id. Make some test cases - if there is missing home_id what will happen, if home_id is not mongoose object id. Test and positive case when everything should work properly
- on route /home POST request we have to provide request with body which contains name, place, description and optional price, size, year. Write positive and negative cases.
- on route /home PUT request we have to provide home_id and body which is similar to the body from the POST request. Write positive and negative scenario cases
- on DELETE /home send request with body home_id. It is similar to GET request.

I do not like the system to return status code 500. I can accept 400 if the request is bad and 404 if the resource is missing. 201 status code for created, 200 for edited and 200 for deleted. 

If you have more questions, write some comments and I will help.

**Comment by edesuccess54** [comment]
can you make the issue more clear enough to understand

**Comment by DamyanBG** [comment]
Hello @edesuccess54 , I am glad to see that you have interest in this app! Now I will change the description and I will provide more accurate information.

**Comment by DamyanBG** [comment]
I am taking this issue.

**Comment by edesuccess54** [comment]
> Hello @edesuccess54 , I am glad to see that you have interest in this app! Now I will change the description and I will provide more accurate information.

Alright 👍

**Comment by DamyanBG** [comment]
I made positive tests.
