### ISSUE TITLE
Home map and coordinates

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-nodejs-be#36]
It is good idea to add coordinates and for the Homes. If somebody wants his home to be visible on the map, he can add the coordinates.

Criteria: add non required fields for the Home model and schema - longitude and latitude.

**Comment by edesuccess54** [comment]
@DamyanBG maybe you take a look at the DB connection. i'm having trouble running the application and so it affects what i would want to contribute to.

**Comment by DamyanBG** [comment]
@edesuccess54 I changed the code related to database connection. You have to create .env file and there you have to write variable called AZURE_DATABASE_CONNECTION_STRING . There you can write your connection string to your local MongoDB database or if you want leave me an email and I will send to you the link to MongoDB hosted on Microsoft Azure Cloud platform. Also, please start the app with npm start dev.

**Comment by edesuccess54** [comment]
@DamyanBG alright let me get your email so i can email you then

**Comment by DamyanBG** [comment]
d.dimitrov.1988@abv.bg
