### ISSUE TITLE
Visitations

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-nodejs-be#37]
Meetings are 1 on 1 or similar things, where 1 person or 1 group of persons go to see the Home for sale from another person or group. The idea behind visitations is to have an event where 1 person or 1 group are selling house, but they want to spend for example 1 hour per week to show their Home for sale or rent to many people. For that we need to implement Visitations, which must contain:

- id
- start_date
- end_date
- organizator_id
- address

Write CRUD operations on /visitation

**Comment by tihomirtx88** [comment]
I have future suggest like idea ,example we can ad like extra fields in this model duration visitation if case we have to many visitation for the same day.

**Comment by DamyanBG** [comment]
Yes, we can implement more logic in the future. You can get familiar with Meetings model too to understand better the logic behind the meetings and visitations. For sure the names of the models can not be 100 % accurate, but we can fix that when we start to make the documentation of the application.
