### ISSUE TITLE
Hashing the user password

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-nodejs-be#47]
On route /user on POST request I can see that the functionality is not good. We have to take password key from the body, to hash it and to store it on the database. I want the field for the User Model to be changed from hashedPassword to password. It is obvious that we store the password and it is hashed. When we take back the User, do not return the password. 

This issue will affect everything in  /user and /users routes.

**Comment by tihomirtx88** [comment]
I will fixed
