### ISSUE TITLE
Linter and code formatter

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-nodejs-be#5]
Make a research for Javascript linters and formatters. Pick something and add it to the project.

**Comment by Farischt** [comment]
Strongly advise you to switch to typescript before the project gets larger !

**Comment by DamyanBG** [comment]
I do not think adding TypeScript gives too much benefits. Good programmers will be able to make good applications without it.

**Comment by DamyanBG** [comment]
#64 code formatter added.

**Comment by rhinoxD** [comment]
!assign

**Comment by rhinoxD** [comment]
Pr to be made to which branch?

**Comment by DamyanBG** [comment]
development
