### ISSUE TITLE
Delete request on User 

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/real-estate-nodejs-be#8]
When I am sending request DELETE on /user with id which do not exists in the database, I am receiving status code 200 and message - Account has been deleted. 

When the User id is not existing the system have to return status code 400 with message - User with this id do not exists.

**Comment by edesuccess54** [comment]
hello @DamyanBG assign the issue to me

**Comment by DamyanBG** [comment]
Good job @edesuccess54 !
